models.py
from __future__ import division

import numpy as np
import string

import otree.models
from otree.db import models
from otree import widgets
from otree.common import Currency as c, currency_range, safe_json
from otree.constants import BaseConstants
from otree.models import BaseSubsession, BaseGroup, BasePlayer

author = 'Hernán Villamizar'

doc = """
Income Inequality and Effort:
This is the introduction to a Tullock Contest in form of a Real Effort Task and Investment decision
It welcomes the participants and helps them trough the first stages
"""


class Constants(BaseConstants):
    name_in_url = 'tullock_income_intro'
    players_per_group = 3
    num_rounds = 2  # first round is with low, second with high wage

    t = 180  # Total Time in seconds available for both solving and staying in switch
    # make sure to change images in instructions to be consistent with max time
    # also instructions tables
    time_in_minutes = t/60

    tokensper_string = 1
    tokensper_string_high = 2
    eurosper_token = c(0.1)  # make sure to change it in both models
    secondsper_token = 10  # if changing this correct SwitchInstructions

    increase_per_string = 4

    # this is a summarized instruction to be shown under each sequence as a reminder:
    instructions_summarized = 'tullock_income_intro/InstructionsSum.html'


class Subsession(BaseSubsession):
    # save setting values as an extra column
    def creating_session(self):
        for p in self.get_players():
            p.time_per_round = Constants.t  # Total Time in seconds available for both solving and staying in switch
            p.tokensper_string = Constants.tokensper_string
            p.tokensper_string_high = Constants.tokensper_string_high
            p.eurosper_token = Constants.eurosper_token
            p.secondsper_token = Constants.secondsper_token
            p.increase_per_string = Constants.increase_per_string


class Group(BaseGroup):

    total_production = models.IntegerField(initial=0)  # define group variable

    # determine total production:

    def set_total_production(self):
        total_production = sum(p.production_strings for p in self.get_players())
        # retrieves a list of all individual productions
        # and sums them up
        self.total_production = total_production

    # determine income:
    def set_incomes(self):
        for p in self.get_players():
            if self.round_number == 2:  # second round is paid to the high wage
                p.income_strings_gross = p.production_strings * Constants.tokensper_string_high
                p.net_income = p.income_strings_gross + p.income_in_switch
            else:
                p.income_strings_gross = p.production_strings * Constants.tokensper_string
                p.net_income = p.income_strings_gross + p.income_in_switch
        for p in self.get_players():
            p.participant.vars[f'net_income_{self.round_number}'] = p.net_income
            print('vars is', p.participant.vars)

    # determine payoffs:
    def set_payoffs(self):
        for p in self.get_players():
            p.earnings = p.net_income
            p.payoff = p.net_income * Constants.eurosper_token


class Player(BasePlayer):

    # save Constants as an extra column for each observation

    time_per_round = models.PositiveIntegerField()  # Total Time in seconds available for both solving and staying in switch

    tokensper_string = models.PositiveIntegerField()
    tokensper_string_high = models.PositiveIntegerField()
    eurosper_token = models.FloatField()
    secondsper_token = models.PositiveIntegerField()

    increase_per_string = models.PositiveIntegerField()

    # give each player a letter for recognition (Important for Feedback and grouping later on)
    def role(self):
        return string.ascii_uppercase[self.id_in_group - 1]

    # Control Instructions Variables
    solution_1 = models.PositiveIntegerField(default=0)
    solution_2 = models.PositiveIntegerField(default=0)

    solution_3 = models.PositiveIntegerField()
    solution_4 = models.PositiveIntegerField()
    solution_5 = models.PositiveIntegerField()

    # Control Instructions High
    solution_6 = models.PositiveIntegerField(default=0)
    solution_7 = models.PositiveIntegerField(default=0)

    solution_8 = models.PositiveIntegerField()
    solution_9 = models.PositiveIntegerField()
    solution_10 = models.PositiveIntegerField()

    # Number of Tasks Solved
    output_trial = models.FloatField(default=0)
    production_strings = models.FloatField(default=0)

    # available income after solving RET
    income_strings_gross = models.FloatField(default=0)
    net_income = models.FloatField(default=0)
    earnings = models.FloatField(default=0)

    # Variable is 1 when entering switch
    switch1 = models.PositiveIntegerField(default=0)

    switch_time = models.PositiveIntegerField(default=0)

    time_in_switch = models.PositiveIntegerField(default=0)

    additional_time = models.PositiveIntegerField(default=0)

    income_in_switch = models.FloatField(default=0)

    total_production = models.FloatField(default=0)

    # Time Needed to Solve Task i in Round j with tjxi

    t001 = models.PositiveIntegerField(default=0)
    t002 = models.PositiveIntegerField(default=0)
    t003 = models.PositiveIntegerField(default=0)
    t004 = models.PositiveIntegerField(default=0)
    t005 = models.PositiveIntegerField(default=0)

    # correct to allow a variable number of tasks
    # for now, created with:
    # for i in range(10, 46):
    # print('t1{} = models.PositiveIntegerField(default=0)'.format(i))

    # def set_time_fields(self):
    #     for i in range(31):
    #         self.participant.vars['t1{}'.format(i)] = models.PositiveIntegerField(default=0)
    #     print(self.participant.vars)

    t101 = models.PositiveIntegerField(default=0)
    t102 = models.PositiveIntegerField(default=0)
    t103 = models.PositiveIntegerField(default=0)
    t104 = models.PositiveIntegerField(default=0)
    t105 = models.PositiveIntegerField(default=0)
    t106 = models.PositiveIntegerField(default=0)
    t107 = models.PositiveIntegerField(default=0)
    t108 = models.PositiveIntegerField(default=0)
    t109 = models.PositiveIntegerField(default=0)
    t110 = models.PositiveIntegerField(default=0)
    t111 = models.PositiveIntegerField(default=0)
    t112 = models.PositiveIntegerField(default=0)
    t113 = models.PositiveIntegerField(default=0)
    t114 = models.PositiveIntegerField(default=0)
    t115 = models.PositiveIntegerField(default=0)
    t116 = models.PositiveIntegerField(default=0)
    t117 = models.PositiveIntegerField(default=0)
    t118 = models.PositiveIntegerField(default=0)
    t119 = models.PositiveIntegerField(default=0)
    t120 = models.PositiveIntegerField(default=0)
    t121 = models.PositiveIntegerField(default=0)
    t122 = models.PositiveIntegerField(default=0)
    t123 = models.PositiveIntegerField(default=0)
    t124 = models.PositiveIntegerField(default=0)
    t125 = models.PositiveIntegerField(default=0)
    t126 = models.PositiveIntegerField(default=0)
    t127 = models.PositiveIntegerField(default=0)
    t128 = models.PositiveIntegerField(default=0)
    t129 = models.PositiveIntegerField(default=0)
    t130 = models.PositiveIntegerField(default=0)
    t131 = models.PositiveIntegerField(default=0)
    t132 = models.PositiveIntegerField(default=0)
    t133 = models.PositiveIntegerField(default=0)
    t134 = models.PositiveIntegerField(default=0)
    t135 = models.PositiveIntegerField(default=0)
    t136 = models.PositiveIntegerField(default=0)
    t137 = models.PositiveIntegerField(default=0)
    t138 = models.PositiveIntegerField(default=0)
    t139 = models.PositiveIntegerField(default=0)
    t140 = models.PositiveIntegerField(default=0)
    t141 = models.PositiveIntegerField(default=0)
    t142 = models.PositiveIntegerField(default=0)
    t143 = models.PositiveIntegerField(default=0)
    t144 = models.PositiveIntegerField(default=0)
    t145 = models.PositiveIntegerField(default=0)

    def set_switch1(self):
        # Time at which switch was entered
        self.switch_time = self.switch1 * (
            self.additional_time + self.t101 + self.t102 + self.t103 + self.t104 + self.t105 +
            self.t106 + self.t107 + self.t108 + self.t109 + self.t110 +
            self.t111 +
            self.t112 +
            self.t113 +
            self.t114 +
            self.t115 +
            self.t116 +
            self.t117 +
            self.t118 +
            self.t119 +
            self.t120 +
            self.t121 +
            self.t122 +
            self.t123 +
            self.t124 +
            self.t125 +
            self.t126 +
            self.t127 +
            self.t128 +
            self.t129 +
            self.t130 +
            self.t131 +
            self.t132 +
            self.t133 +
            self.t134 +
            self.t135 +
            self.t136 +
            self.t137 +
            self.t138 +
            self.t139 +
            self.t140 +
            self.t141 +
            self.t142 +
            self.t143 +
            self.t144 +
            self.t145
        )

        # This variable determines the total time spent in switch
        self.time_in_switch = self.switch1 * (Constants.t - self.switch_time)

        # This variable determines the tokens per string received
        self.income_in_switch = self.time_in_switch / Constants.secondsper_token

        # This is the sum of strings + production in switch
        self.total_production = self.production_strings + self.income_in_switch

templates/tullock_income_intro/Feedback.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Feedback Letter Counting Task Round 1.{{ subsession.round_number }}
{% endblock %}

{% block content %}


<div class="card">
  <div class="card-header text-white bg-primary mb-3">Your earnings in this round
      {% if subsession.round_number == 1 %}
      (Wage: 1 Token per Sequence)
      {% else %}
      (Wage: 2 Token per Sequence)
      {% endif %}
      :</div>
  <div class="card-body">
    You solved {{ player.production_strings|floatformat:0 }} sequences which earns you <strong>{{ player.income_strings_gross|c|floatformat:0 }}</strong> Tokens.<br>
    You spent {{player.time_in_switch}} seconds in the <em>switch mode</em> which earns you <strong>{{player.income_in_switch|c|floatformat:1}}</strong> Tokens.<br><br>
    Your total earnings in this round are therefore <strong>{{player.net_income|c|floatformat:1}}</strong> Tokens. <br>
  </div>
</div>

    <br>
        {% if subsession.round_number == 2 %}
    <div class="card">
  <div class="card-header text-white bg-info mb-3">Your earnings in the previous round (Wage: 1 Token per Sequence):</div>
  <div class="card-body">
    You solved {{ production_strings_last|floatformat:0 }} sequences which earns you <strong>{{ income_strings_last|c|floatformat:0 }}</strong> Tokens.<br>
    You spent {{time_in_switch_last}} seconds in the <em>switch mode</em>
      which earns you <strong>{{income_in_switch_last|c|floatformat:1}}</strong> Tokens.<br><br>
    Your total earnings in this round are therefore <strong>{{income_last|c|floatformat:1}}</strong> Tokens. <br>
  </div>
</div>

    {% endif %}
<br>
{% next_button %}

{% endblock %}

templates/tullock_income_intro/HighWageInstructions.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load humanize %}


{% block title %}
    High Wage Earnings
{% endblock %}

{% block content %}
<hr>
<div class="card bg-light instructions">
    <div class="card-body">
    <p>
      The following task is similar to the last one, only that <strong> you will earn {{ Constants.tokensper_string_high|apnumber }}
        Tokens</strong> (instead of {{ Constants.tokensper_string|apnumber }}) per correctly solved sequence.
    </p>
    <p> <U>Remember:</U> At any time, you have the option to change to the <strong><em>switch mode</em></strong>. In this mode, you will earn <strong>1 Token
        per {{ Constants.secondsper_token|apnumber }} seconds</strong> without solving any tasks. For instance, spending 13 seconds in the
        <strong><em>switch mode</em></strong> earns you 1.3 Tk. Given the higher wage in this round, it is advisable to go later
        into "switch" mode.
        <div class="alert alert-warning" role="alert">
        <U>Important:</U> Once you are in the <strong><em>switch mode</em></strong> you cannot go back to the letter counting task!
        </div></p>
    <p>
        Are you ready to proceed?
    </p>
    </div>
</div>

    {% next_button %}

    {% endblock %}

templates/tullock_income_intro/InstructionsSum.html
{% load otree staticfiles %}

<div class="card">
    <div class="card-header text-white bg-primary mb-3"> Instructions </div>
    <div class="card-body">
    <p>
        Your task is to count how many <strong> "a"s </strong> there are in the sequence of characters currently displayed.
    </p>
    <p>
        {% if subsession.round_number > 1 %}
            Per correctly solved sequence you will get {{ Constants.tokensper_string_high }}
            Token.
            {% else %}
            Per correctly solved sequence you will get {{ Constants.tokensper_string }} Token.
        {% endif %}
        In the <strong> switch mode </strong>
        you will get 1 token per each {{ Constants.secondsper_token }} seconds in "switch".
    </p>
    <p>
        <strong>This round lasts {{ Constants.time_in_minutes|floatformat:0 }} Minutes.</strong>
    </p>
    </div>
</div>

templates/tullock_income_intro/Introduction.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Introduction
{% endblock %}

{% block content %}
<hr>
<div class="card bg-light instructions">
    <div class="card-body">
     <p>
        Thank you for taking part in this experiment.</p>
    <p>
        Please read the instructions carefully. They are identical for all participants.<br>
        You are not allowed to communicate with other participants during the experiment.
        Using the cell phone is also prohibited. Please switch it off.
    </p>
    <p>
        In case anything is unclear, please raise your hand. We will come to your desk and answer your questions in private.<br>
    </p>
    <p>
        You will earn money during this experiment and you will receive your earnings in cash immediately after
        this session is finished. How much money you earn depends on the actions you and the other participants take.</p>
    <p>
        To make you familiar with the task you are going to be asked to perform, the next pages will show you the instructions
        and a trial round. At every stage, make sure you only proceed when you have understood the instructions.
        You will not be able to go back.</p>
    </div>
</div>

    <br>
    Are you ready to proceed?
    <br>
    <br>
    {% next_button %}
{% endblock %}

templates/tullock_income_intro/RET.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}


{% block styles %}
    <link href="{% static "tullock_income_intro/css/Round.css" %}" rel="stylesheet">
    <link href="{% static "tullock_income_intro/css/bootstrap-tour-standalone.min.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Letter Counting Task Round 1.{{ subsession.round_number }}
{% endblock %}

{% block content %}

<div class="jumbotron">

<span class="badge badge-primary"  data-toggle="tooltip" data-placement="top" title="Time spent in current sequence">
<span id="min">00</span>:<span id="sec">00</span>
</span>

    <br>
    <span class="badge badge-success" id="number_strings"  data-toggle="tooltip" data-placement="bottom" title="Number of sequences solved" >00</span>

<div id="string">
</div>

<br>

<input type="number" id="player_guess" size="4" autofocus>
</input> &nbsp;

<br>

<input type="hidden" name="production_strings" id="id_production_strings"/>

<p align="right">


<!-- "Switch" Confirmation -->
<button type="button" id="switch_modal" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  SWITCH
</button>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to go into "switch" mode? Once you are in "switch" you cannot go back to solving sequences!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" id="Switch_button" data-dismiss="modal">Switch</button>
      </div>
    </div>
  </div>
</div>
</p>


</div>




<!-- "Switch" Mode -->

<div id="Switch_mode" class="Switch_mode">
    <div class="card">
    <div class="card-header text-white bg-primary mb-3">
        <h5>You are now in the "Switch" mode</h5>
        </div>
        <div class="card-body">
        <p>
            You solved <span class="badge badge-success"> <span name="sequences_solved" id="sequences_solved"></span> </span> sequences.
        </p>

        Your earnings from "Switch" mode are:
        <br>
        <h3>
        <span class="badge badge-primary"><span id="token_counter">00</span> Tokens
        </span>
        </h3>
        </div>
    </div>
    </div>
</div>

    <br>

<input type="hidden" name="switch1" id="id_switch1"/>

{{ form.errors }}

    {% include Constants.instructions_summarized %}

{% endblock %}

{% block scripts %}

    {% comment %}
<script type="text/javascript" src="{% static 'tullock_income_intro/js/bootstrap-tour-standalone.min.js' %}"></script>


    <!-- Uncomment to initialize a tour of all elements in the screen (counters, switch, etc -->
    {% if subsession.round_number == 1 %}
<script type="text/javascript" src="{% static 'tullock_income_intro/js/Tour-RET.js' %}"></script>
    {% endif %}
    {% endcomment %}

        <!-- this needs to be in a separate file. -->
<script>


//this initiates the tooltip mouseover to explain the counters
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
//

var string_list = {{ session.vars.string_list|json }};
var a_count = {{ session.vars.a_count|json }};
var length_1 = a_count.length;

var me = me || {};
me.index = null;
me.guess = null;
me.timer = null;
me.pad = null;
me.settime = null;
me.resettime = null;
me.check = null;
me.makeguess = null;

// This function adds an additional "0" left to single digit numbers for formatting reasons, not for functionality
// is called repeatedly from within settime and resettime functions
me.pad = function(val) {
    return val > 9 ? val : "0" + val;
};

// This function first sets the time to zero and then increments the counter every 1000ms by 1. Minutes (sec modulo 60) and seconds separately
// only called once at window.onload
me.settime = function() {
    me.sec = 0;
    me.timer = setInterval(function () {
        document.getElementById("sec").innerHTML = me.pad(++me.sec % 60);
        document.getElementById("min").innerHTML = me.pad(parseInt(me.sec / 60, 10));
        }, 1000)
};

// This function stops the active timer and sets the display to 00:00. Subsequently, the timer is restarted.
// is called by function makeguess on keydown event xxx -> potentially contributing to our problem, removed for testing
me.resettime = function(){
    clearInterval(me.timer);
    document.getElementById("sec").innerHTML = "00";
    document.getElementById("min").innerHTML = "00";

    me.sec = 0;
    me.timer = setInterval(function () {
        document.getElementById("sec").innerHTML = me.pad(++me.sec % 60);
        document.getElementById("min").innerHTML = me.pad(parseInt(me.sec / 60, 10));
        }, 1000)
};

// This function checks whether the correct number of "a"s was provided
// resets the input text field to empty
me.check = function(x) {
    document.getElementById("player_guess").value = "";

    var el = document.createElement("input")
    el.type = "hidden";
    if (me.index+1 < 10){
        el.name = "t10" + (me.index+1);
    } else{
        el.name = "t1" + (me.index+1);
    }
    el.value = me.sec;
    el.id = el.name;

    var answers = document.getElementById("id_production_strings");
    answers.appendChild(el);

    if (x === a_count[me.index]) {
        me.makeguess(me.index+1);
        me.resettime();
    } else {
        me.makeguess(me.index);
    }
};

// This function loads and displays the next string
// it also counts the number of strings correctly solved
me.makeguess = function(x) {
    if (x >= length_1) {
        alert("Error");
    } else {
        me.index = x;

        var string = document.getElementById("string");
        string.innerHTML = string_list[x];

        number_strings = x;
        document.getElementById("number_strings").innerHTML = number_strings;

        document.getElementById("id_production_strings").setAttribute("value",me.index);
    }
};


// This function is called by the keydown event handler
// it resets the time and triggers the checking function
function keyDownTextField(e) {
  var keyCode = e.keyCode;
  if(keyCode==13) {
    event.preventDefault();
    var wert = document.getElementById("player_guess").value;
    me.guess = parseInt(wert);
    me.check(me.guess);
    }
}

// This function is called by the keyup event handler and only blocks the enter button
function keyUpTextField(e) {
  var keyCode = e.keyCode;
  if(keyCode==13) {
    event.preventDefault();
  }
}

// This function is called by the keypress event handler and only blocks the enter button
function keyPressTextField(e) {
  var keyCode = e.keyCode;
  if(keyCode==13) {
    event.preventDefault();
  }
}

// The following sends the participant to "switch" mode

document.getElementById("Switch_button").addEventListener("click", function() {
    event.preventDefault();
    var el = document.createElement("input");
    el.type = "hidden";
    el.name = "additionaltime1";
    el.value = me.sec;
    el.id = el.name;
    var answers = document.getElementById("id_production_strings");
    answers.appendChild(el);
    var pattern = document.getElementsByClassName("jumbotron")[0];
        pattern.classList.add("d-none");
    var switchmode = document.getElementsByClassName("Switch_mode");
        switchmode[0].classList.remove("d-none");
    var switch1 = 1;
        document.getElementById("id_switch1").setAttribute("value",switch1);

    var tokens = 0;
    var counter = document.getElementById('token_counter');

    // This functions counts the earnings in "switch" dynamically and shows the total of strings solved
    function incrementSeconds() {
    tokens += 0.1;
    counter.innerText = Math.round( tokens * 10 ) / 10;
    }

    var cancel = setInterval(incrementSeconds, 1000);

    var sequences_solved = number_strings;
    var sequences = document.getElementById("sequences_solved");
    sequences.innerText = sequences_solved;

});

// displays the first string and starts the counter
// Importantly, the event handlers are only called here once!!!
window.onload = function(){
    me.makeguess(0);
    me.settime();
    var switchmode = document.getElementsByClassName("Switch_mode");
    switchmode[0].classList.add("d-none");
    document.addEventListener("keydown", keyDownTextField, false);
    document.addEventListener("keyup", keyUpTextField, false);
    document.addEventListener("keypress", keyPressTextField, false);
}

    </script>
{% endblock %}

templates/tullock_income_intro/Round0.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block styles %}
    <link href="{% static "tullock_income_intro/css/Round.css" %}" rel="stylesheet">
    <link href="{% static "tullock_income_intro/css/bootstrap-tour-standalone.min.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Trial Round
{% endblock %}

{% block content %}
<hr>

<div class="done_text" id="done_text">
</div>

<div class="jumbotron">

<span class="badge badge-primary" id="step_1">
<span id="min">00</span>:<span id="sec">00</span>
</span>

<div id="string">
</div>

<br>

<input type="number" id="player_guess" size="4" autofocus>
</input> &nbsp;


<br>

<input type="hidden" name="output_trial" id="id_output_trial"/>




</div>
<div class="next_container">
    <input class="d-none btn btn-primary btn-large btn-primary" id="next-button" type="submit" value="Continue">
</div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'tullock_income_intro/js/Round0.js' %}"></script>
    <script type="text/javascript" src="{% static 'tullock_income_intro/js/bootstrap-tour-standalone.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'tullock_income_intro/js/Tour-Trial.js' %}"></script>
{% endblock %}

templates/tullock_income_intro/StartSubmit.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Start Confirmation
{% endblock %}

{% block content %}
<hr>

    <div class="jumbotron">
    {% if subsession.round_number == 1 %}
    <p>From the next screen on you will have the opportunity to earn money
        as explained in the screens before.
        {% else %}
        In the next screen you will have the opportunity to earn money as explained in the screens before.
    {% endif %}
    </p>
    <h1>Are you ready to start?</h1>
        <p>
            Pressing the <span class="badge badge-danger">Start</span> button will start the letter counting task
        </p>
        <br>
        <br>
        <br>
    <button class="btn btn-danger btn-block">Start</button>
    </div>


{% endblock %}

templates/tullock_income_intro/SwitchInstructions.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load humanize %}

{% block title %}
    Earnings and "Switch"
{% endblock %}

{% block content %}
<hr>
<div class="card bg-light instructions">
    <div class="card-body">
    <p>
        In the following rounds of counting letters you can earn money.
        <strong>For each sequence in which you count the correct number of "a"s </strong>
        you will receive <strong>{{ Constants.tokensper_string }} Token</strong> (Tk). That is your wage.
        At the end of this session, one Token will be converted into <strong>{{ Constants.eurosper_token }} Euro</strong>.
    </p>
    <p>
        You will start solving short sequences. After each sequence you solve, the <strong>length of the sequences will increase
        by {{ Constants.increase_per_string|apnumber }} characters</strong>. The sequences presented and their order are identical for all participants.
        Also, all participants have to count the same letter ( <strong>a</strong> ) such that <strong>everybody faces the same difficulty in solving the task</strong>.
    </p>
    <p>
        At any time, you have the option to change to the <strong><em>switch mode</em></strong>. In this mode, you will earn <strong>1 Token
        per {{ Constants.secondsper_token|apnumber }} seconds</strong> without solving any tasks. For instance, spending 13 seconds in the
        <strong><em>switch mode</em></strong> earns you 1.3 Tk. Since the difficulty of the task increases,
        at a certain point you will earn more from staying in the <em>switch mode</em>
        than from solving tasks. Think therefore about when it is best for you change to the <strong><em>switch mode.</em></strong>
        <p>
        <strong> Each round lasts {{ Constants.time_in_minutes|floatformat:0 }} minutes ({{ Constants.t }} seconds)</strong> in which you can either solve tasks or spend time in
        "switch" mode. A timer in yellow above the sequence will show you the time left in the current round and a green counter
        will tell you how many sequences you have solved so far.
    </p>
        <br>
        <div class="alert alert-warning" role="alert">
        <U>Important:</U> Once you are in the <strong><em>switch mode</em></strong> you cannot go back to the letter counting task!
        </div>
        <br>
    <p>
        Below this panel you will find an example of how earnings from "Letter Counting" and "Switch" add up. Farther below you will find two annotated images
        showing you all the new relevant elements (Page Timer, Counter of Solved Sequences, and Switch Button).
    </p>
    </p>
    </div>
</div>

    <div class="card">
       <div class="card-header text-white bg-primary mb-3">
        <h5>Earnings Example</h5>
        </div>
  <div class="card-body">
    Here you can see an illustrative example of possible earnings:
  </div>
<!-- Begin Table -->
<table class="table">
  <thead>
  <tr>
    <th class="tg-s6z2">Quantity (Sequences)</th>
    <th class="tg-s6z2">Time (sec)</th>
    <th class="tg-s6z2">Activity</th>
    <th class="tg-s6z2">Payment Key</th>
    <th class="tg-s6z2">Earnings (Token)</th>
  </thead>
  </tr>
  <tr>
    <td class="tg-s6z2">24</td>
    <td class="tg-s6z2">90</td>
    <td class="tg-s6z2">Letter Count</td>
    <td class="tg-s6z2">For Solved Sequences</td>
    <td class="tg-s6z2">24</td>
  </tr>
  <tr>
    <td class="tg-s6z2">--</td>
    <td class="tg-s6z2">90</td>
    <td class="tg-s6z2">"Switch" Mode</td>
    <td class="tg-s6z2">For Spent Seconds</td>
    <td class="tg-s6z2">9</td>
  </tr>
  <tfoot>
  <tr>
    <td class="tg-s6z2"><strong>Total</strong></td>
    <td class="tg-s6z2">{{ Constants.t }}</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2">33</td>
  </tr>
  </tfoot>
</table>
    </div>
<br>

<hr>

<div class="card bg-light instructions">
    <div class="card-body">
    An example screen is shown below, showing you all the new relevant elements (Page Timer, Counter of Solved Sequences, and Switch Button).
    </div>
    </div>
    <div class="card">
    <div class="card-header text-white bg-primary mb-3">Letter Count screen</div>
    <img src="{% static 'tullock_income_intro/task_inst_switch.png' %}" class="img-thumbnail"
         alt="Responsive image">
    </div>

    <hr>

<div class="card bg-light instructions">
    <div class="card-body">
    Note: to ensure that you do not enter the "switch" mode by mistake you will be asked for confirmation. An example screen is shown below.
    </div>
    </div>
    <div class="card">
    <div class="card-header text-white bg-primary mb-3">"Switch" confirmation screen</div>
    <img src="{% static 'tullock_income_intro/6-3-Trial-Round-Switch-Conf.png' %}" class="img-thumbnail"
         alt="Responsive image">
    </div>

    <br>

    <br>
    <h4>Are you ready to proceed?</h4>
    {% next_button %}

{% endblock %}